name: Test Release

on:
  schedule:
    - cron:  '0 0 */3 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Staging
        run: |
          echo "hola" > test
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: Proton
          files: |
            ./test
