name: Proton-GE Test WoW64 CI

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Download artifact Bootstrap
        id: download-artifact-boot
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          workflow: bootstrap_wow64.yml
          workflow_conclusion: success
          path: /opt
      - name: Download artifact proton
        id: download-artifact-proton
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          workflow: proton-gitint.yml
          workflow_conclusion: success
          path: ./
      - name: Build Wine
        run: |
          # Debug: List working directory and initial state
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          
          # Update and install dependencies
          sudo apt update
          sudo apt install -y debootstrap perl git wget xz-utils bubblewrap autoconf automake libtool build-essential gcc-14 g++-14 mingw-w64
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          
          # Check and extract bootstrap
          echo "Checking for bootstrap file..."
          ls -la /opt/Bootstraps\ WoW64/ || echo "Bootstrap directory not found"
          if [ -f "/opt/Bootstraps WoW64/bootstraps_wow64.tar.xz" ]; then
            echo "Extracting bootstrap..."
            sudo tar -C /opt -xpf "/opt/Bootstraps WoW64/bootstraps_wow64.tar.xz"
          else
            echo "ERROR: Bootstrap file not found!"
            exit 1
          fi
          
          # Debug bootstrap contents
          echo "Contents of /opt/chroots/noble64_chroot:"
          ls -la /opt/chroots/noble64_chroot || echo "Directory not found"
          
          # Create BUILD_DIR
          mkdir -p "${HOME}/build_wine"
          
          # Debug: Check Proton source
          echo "Checking for Proton source directory..."
          ls -la | grep "PROTON-GE SRC WoW64" || echo "Proton source directory not found"
          if [ -d "PROTON-GE SRC WoW64" ]; then
            mv "PROTON-GE SRC WoW64" "${HOME}/build_wine/wine"
            sudo chmod -R +x "${HOME}/build_wine/wine"
          else
            echo "No artifact found, cloning Proton-GE source..."
            git clone https://github.com/gloriouseggroll/proton-ge-custom ${HOME}/build_wine/wine
            cd ${HOME}/build_wine/wine
            git checkout proton_8.0
            sudo chmod -R +x ${HOME}/build_wine/wine
          fi
          
          # Debug source contents
          echo "Contents of ${HOME}/build_wine/wine:"
          ls -la ${HOME}/build_wine/wine
          echo "Checking for critical files:"
          ls -la ${HOME}/build_wine/wine/configure.ac ${HOME}/build_wine/wine/dlls/ntdll/unix/thread.c || echo "One or more critical files missing"
          
          # Copy patch files
          echo "Copying patch files..."
          ls -la *.patch protonprep-valve-staging.sh || echo "One or more patch files missing"
          cp proton-GE-drivepatch.patch protonprep-valve-staging.sh termux-wine-fix-protonge.patch \
             path-patch-universalPGE.patch ndis_proton.patch wine-virtual-memory-proton.patch \
             esync-GE.patch looserexceptionhandling_protonGE.patch "${HOME}/build_wine" || {
            echo "Error: One or more patch files missing!"
            ls -la
            exit 1
          }
          
          cd "${HOME}/build_wine/wine"
          echo "Now in directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          
          # Initialize git and setup repository
          git init
          git remote add origin https://github.com/gloriouseggroll/proton-ge-custom
          git fetch origin
          git reset --hard origin/proton_8.0
          
          # Debug git reset
          echo "Contents after git reset:"
          ls -la
          ls -la configure.ac dlls/ntdll/unix/thread.c || echo "Critical files missing after git reset"
          
          # Copy patches
          echo "Setting up patches..."
          cp ../proton-GE-drivepatch.patch ./wine-staging/patches/ntdll-ext4-case-folder/0002-ntdll-server-Mark-drive_c-as-case-insensitive-when-c.patch
          cp ../protonprep-valve-staging.sh ./patches/protonprep-valve-staging.sh
          mkdir -p ./patches/termux-patches
          cp ../termux-wine-fix-protonge.patch ./patches/termux-patches/
          cp ../path-patch-universalPGE.patch ./patches/termux-patches/
          cp ../ndis_proton.patch ./patches/termux-patches/
          cp ../wine-virtual-memory-proton.patch ./patches/termux-patches/
          cp ../esync-GE.patch ./patches/termux-patches/
          cp ../looserexceptionhandling_protonGE.patch ./patches/termux-patches/
          
          sudo chmod +x -R ./patches/termux-patches
          sudo chmod +x ./patches/protonprep-valve-staging.sh
          
          echo "Running protonprep-valve-staging.sh..."
          bash -x ./patches/protonprep-valve-staging.sh
          
          # Apply Makefile.in modifications
          if [ -f "./Makefile.in" ]; then
            sed -i 's/tar.gz/tar.xz/' ./Makefile.in
            sed -i 's/tar -cvzf $(BUILD_NAME).tar.xz $(BUILD_NAME)/tar -cvzf \$\(BUILD_NAME\).tar.xz \$\(BUILD_NAME\)\/*/' ./Makefile.in
            sed -i -E "$(sed -n '/mv $(REDIST_DIR) $(BUILD_NAME)/=' ./Makefile.in) i\\\tmv \$\(REDIST_DIR\)\/files \$\(REDIST_DIR\)\/wine" ./Makefile.in
          else
            echo "WARNING: Makefile.in not found"
          fi
          
          # Modify winetricks if present
          if [ -f "protonfixes/winetricks" ]; then
            sed -i 's/W_TMP_EARLY=.*/\W_TMP_EARLY="\/data\/data\/com.gebox.emu\/files\/usr\/tmp\"/' protonfixes/winetricks
          else
            echo "WARNING: protonfixes/winetricks not found"
          fi
          
          # Modify default_pfx.py if present
          if [ -f "default_pfx.py" ]; then
            W_LINE=$(sed -n '/ -w/=' default_pfx.py 2>/dev/null)
            if [ -n "$W_LINE" ]; then
              W_LINE=$((W_LINE - 2))
              echo "Found -w flag at line $W_LINE, modifying default_pfx.py"
              sed -i -E "${W_LINE} i\\    subprocess.run(runtime_args + [\"/bin/bash\", \"-c\", \"mkdir -p build && cd build\"])" default_pfx.py
            else
              echo "WARNING: Could not find -w pattern in default_pfx.py"
            fi
          else
            echo "WARNING: default_pfx.py not found"
          fi
          
          # Run configure.sh
          echo "Looking for configure.sh..."
          if [ -f "../configure.sh" ]; then
            echo "Running configure.sh..."
            ../configure.sh --build-name=wine-action-proton-GE --container-engine=podman || {
              echo "ERROR: configure.sh failed"
              exit 1
            }
          else
            echo "ERROR: configure.sh not found!"
            find "${HOME}/build_wine" -name "configure.sh"
            exit 1
          fi
          
          # Download and run build_protonGE.sh
          echo "Downloading build_protonGE.sh..."
          curl -L -o "${HOME}/build_wine/wine/build_protonGE.sh" https://github.com/asklo339/wineCustomBuild/raw/refs/heads/master/build_protonGE.sh
          if [ -f "${HOME}/build_wine/wine/build_protonGE.sh" ]; then
            echo "build_protonGE.sh downloaded successfully!"
            chmod +x "${HOME}/build_wine/wine/build_protonGE.sh"
          else
            echo "ERROR: Failed to download build_protonGE.sh!"
            exit 1
          fi
          
          # Run build_protonGE.sh
          echo "Running build_protonGE.sh..."
          bash -x ./build_protonGE.sh
          
          # Debug build output
          echo "Checking for build output..."
          ls -la ${HOME}/build_wine
          ls -la ${HOME}/build_wine/wine
          
          # Move result to workspace
          if [ -f "${HOME}/build_wine/wine/wine-action-protonGE.tar.xz" ]; then
            mv "${HOME}/build_wine/wine/wine-action-protonGE.tar.xz" .
            echo "Build completed successfully!"
          else
            echo "ERROR: Build output not found!"
            exit 1
          fi
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: Proton
          files: |
            ./wine-action-protonGE.tar.xz
